import type { Metadata } from "next";
import { Providers } from "@/utils/uiprovider";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/partials/Header";
import { ThemeProvider } from "@/utils/themeprovider";
import Footer from "@/components/partials/Footer";

export const metadata: Metadata = {
  title: "ThenaWork",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-full">
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <Providers>
            {children}
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
